[theme]
primaryColor = "#1f77b4"             # cor principal de botões e destaques
backgroundColor = "#f5f5f5"          # fundo da página
secondaryBackgroundColor = "#ffffff" # fundo dos cartões
textColor = "#333333"                # cor do texto
font = "sans serif"                  # ou "serif", "monospace"
